on:
  push:
    branches:
      - main
name: Docker build and push
jobs:
  publish_docker_image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: old-home
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/old-home/php-fpm:latest \
            --tag ghcr.io/old-home/php-fpm:$(echo $GITHUB_SHA | head -c7) \
            .
      - name: Push Docker Image
        run: |
          docker push "ghcr.io/old-home/php-fpm:latest"
          docker push "ghcr.io/old-home/php-fpm:$(echo $GITHUB_SHA | head -c7)"

